from flask import Flask, request, jsonify
import requests
import firebase_admin
from firebase_admin import credentials, db
import traceback
import re
import cv2
import numpy as np


import os

latest_image = None
processed_latest_image = None

app = Flask(__name__)

# Firebase Authentication
cred = credentials.Certificate("key.json")

# ✅ FIXED: You left the databaseURL as "your-db" earlier! 
# We've updated it to match your actual Google Project ID!
firebase_admin.initialize_app(cred, {
    "databaseURL": "https://gst-server-491905-default-rtdb.firebaseio.com/"
})

# ==========================================
# 🛑 GOOGLE VISION COMPLETELY REMOVED! 🛑
# We are now using OCR.space - 100% Free, NO Credit Cards!
# ==========================================

def extract_text(image_bytes):
    # Free API endpoint for OCR.space
    api_url = 'https://api.ocr.space/parse/image'
    
    # Private OCR.space Key generated by User
    api_key = 'K89293385788957' 
    
    # Send our cropped, perfectly flattened image explicitly as a JPEG
    files = {"file": ("invoice.jpg", image_bytes, "image/jpeg")}
    
    # Settings: Engine 1 usually reads text best. isTable=True helps with aligned bills.
    data = {
        "apikey": api_key,
        "language": "eng",
        "OCREngine": 1,
        "scale": "true",
        "isTable": "true"
    }
    
    try:
        response = requests.post(api_url, files=files, data=data)
        result = response.json()
        
        # Did the API throw a processing error?
        if result.get("IsErroredOnProcessing"):
            error_msg = result.get("ErrorMessage")
            print("❌ OCR.space API Error:", error_msg)
            return f"API ERROR: {error_msg}"
            
        # Successfully parsed!
        parsed_results = result.get("ParsedResults", [])
        if parsed_results:
            return parsed_results[0].get("ParsedText", "")
            
        return "BLANK RESULT"
        
    except Exception as e:
        print("🔥 OCR Exception:", str(e))
        return f"EXCEPTION: {str(e)}"

# GST Extraction
def find_gst(text):
    # Try strict exact match first
    match = re.findall(r"\d{2}[A-Z]{5}\d{4}[A-Z]\d[Z][A-Z\d]", text)
    if match: return match[0]
    
    # Blurry digital text often confuses OCR kerning, causing it to insert random
    # spaces inside continuous strings (e.g., "27AA B CF 8078").
    # We remove ALL whitespace characters to form one giant continuous string block.
    clean_text = re.sub(r'\s+', '', text)
    
    # Try strict match on the spaceless text
    match_clean = re.findall(r"\d{2}[A-Z]{5}\d{4}[A-Z]\d[Z][A-Z\d]", clean_text)
    if match_clean: return match_clean[0]
    
    # Fallback: Look for the literal word "GSTIN". 
    # We use [^A-Za-z0-9]* to capture and ignore any random punctuation (like colons, semicolons, dashes) 
    # that the OCR might have incorrectly interpreted between "GSTIN" and the number.
    fallback = re.search(r"GSTIN[^A-Za-z0-9]*([A-Za-z0-9\u00df]{12,18})", clean_text, re.IGNORECASE)
    if fallback:
        extracted = fallback.group(1).upper()
        # Replace common OCR misreads
        extracted = extracted.replace("ß", "B")
        return extracted
        
    return None

# 🔥 BULLETPROOF AUTO-ZOOM & BLUR DETECTION
def crop_invoice(image_bytes):
    try:
        nparr = np.frombuffer(image_bytes, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        if img is None:
            return False, image_bytes

        # Grayscale conversion
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # 🟢 VERIFY IMAGE IS NOT BLURRY (Matches ESP32 logic)
        variance = cv2.Laplacian(gray, cv2.CV_64F).var()
        print(f"📷 Image Sharpness Variance: {variance:.2f}") # Helps debugging on Render
        
        # ESP32-CAM OV2640 lenses are naturally a bit soft. 
        # A threshold of 10 is much more forgiving than 40, especially for phone screens.
        if variance < 10.0:
            return "BLUR", image_bytes

        # Apply slight blur just for edge detection algorithms
        gray_blurred = cv2.GaussianBlur(gray, (5, 5), 0)
        edges = cv2.Canny(gray_blurred, 75, 200)

        cnts = cv2.findContours(edges, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
        contours = cnts[0] if len(cnts) == 2 else cnts[1]
        
        contours = sorted(contours, key=cv2.contourArea, reverse=True)[:5]
        
        screen_cnt = None
        for cnt in contours:
            peri = cv2.arcLength(cnt, True)
            approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)
            if len(approx) == 4 and cv2.contourArea(cnt) > 5000:
                screen_cnt = approx
                break
                
        if screen_cnt is None:
            return False, image_bytes
            
        pts = screen_cnt.reshape(4, 2)
        rect = np.zeros((4, 2), dtype="float32")
        s = pts.sum(axis=1)
        rect[0] = pts[np.argmin(s)]
        rect[2] = pts[np.argmax(s)]
        diff = np.diff(pts, axis=1)
        rect[1] = pts[np.argmin(diff)]
        rect[3] = pts[np.argmax(diff)]

        (tl, tr, br, bl) = rect

        widthA = np.sqrt(((br[0] - bl[0]) ** 2) + ((br[1] - bl[1]) ** 2))
        widthB = np.sqrt(((tr[0] - tl[0]) ** 2) + ((tr[1] - tl[1]) ** 2))
        maxWidth = max(int(widthA), int(widthB))

        heightA = np.sqrt(((tr[0] - br[0]) ** 2) + ((tr[1] - br[1]) ** 2))
        heightB = np.sqrt(((tl[0] - bl[0]) ** 2) + ((tl[1] - bl[1]) ** 2))
        maxHeight = max(int(heightA), int(heightB))

        dst = np.array([
            [0, 0],
            [maxWidth - 1, 0],
            [maxWidth - 1, maxHeight - 1],
            [0, maxHeight - 1]], dtype="float32")

        M = cv2.getPerspectiveTransform(rect, dst)
        warped = cv2.warpPerspective(img, M, (maxWidth, maxHeight))

        warped_gray = cv2.cvtColor(warped, cv2.COLOR_BGR2GRAY)
        
        is_success, buffer = cv2.imencode(".jpg", warped_gray)
        if is_success:
            return True, buffer.tobytes()
            
    except Exception as e:
        print("Safely ignoring crop error:", e)
        
    return False, image_bytes

# 🔥 FINAL LOGIC
# 🔥 FINAL LOGIC
def is_invoice(text):
    if len(text) < 15:  # Extremely forgiving
        return False

    score = 0
    t = text.lower()
    
    # Dictionary of common invoice/corporate words and their point values
    keywords = {
        "invoice": 3, "bill": 3, "gst": 3, "tax": 2, "retail": 2, 
        "order": 2, "pan": 2, "supply": 2, "total": 1, "date": 1,
        "amount": 1, "number": 1, "private": 1, "limited": 1, 
        "warehouse": 1, "details": 1
    }
    
    for word, points in keywords.items():
        if word in t:
            score += points
            
    if find_gst(text): 
        score += 5

    # 4 points is passing. Example: "private"(1) + "limited"(1) + "warehouse"(1) + "number"(1) = 4 checks out!
    return score >= 4


@app.route('/')
def home():
    return "GST AI SERVER RUNNING. Live viewer available at: <a href='/dashboard'>/dashboard</a>"

@app.route('/dashboard')
def dashboard():
    return """
    <html>
      <head>
        <title>ESP32-CAM Live View</title>
        <meta http-equiv="refresh" content="10"> <!-- Auto refresh every 10 seconds -->
        <style>
          body { font-family: 'Inter', sans-serif; text-align: center; background: #0f172a; color: #f8fafc; margin: 0; padding: 40px;}
          h1 { margin-bottom: 5px; font-size: 32px;}
          p { color: #94a3b8; font-size: 14px; margin-bottom: 30px;}
          .image-wrapper { display: flex; justify-content: center; gap: 30px; flex-wrap: wrap; margin-top: 20px;}
          .image-card { background: #1e293b; border: 1px solid #334155; border-radius: 12px; padding: 20px; box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1); }
          .image-card img { max-width: 480px; width: 100%; height: auto; border-radius: 8px; border: 1px solid #475569; }
          .image-card h2 { margin-top: 0; font-size: 18px; color: #38bdf8; font-weight: 600;}
          .btn { padding: 12px 24px; font-size: 16px; font-weight: bold; background: #3b82f6; color: white; border: none; border-radius: 8px; cursor: pointer; transition: 0.3s; }
          .btn:hover { background: #2563eb; }
        </style>
      </head>
      <body>
        <h1>Invoice Scanner Live Feed</h1>
        <p>Auto-refreshes every 10 seconds</p>
        <button class="btn" onclick="location.reload()">Manual Refresh</button>
        <div class="image-wrapper">
          <div class="image-card">
            <h2>Raw Image from Camera</h2>
            <img src="/latest?t=" onload="this.src='/latest?t='+new Date().getTime()" alt="Raw Capture" onerror="this.onerror=null; this.src=''; ">
          </div>
          <div class="image-card">
            <h2>Auto-Cropped for OCR</h2>
            <img src="/latest_processed?t=" onload="this.src='/latest_processed?t='+new Date().getTime()" alt="Processed Cropped Capture" onerror="this.onerror=null; this.src=''; ">
          </div>
        </div>
      </body>
    </html>
    """


@app.route('/latest')
def get_latest():
    if latest_image:
        return app.response_class(latest_image, mimetype='image/jpeg')
    return "No ESP32 connection yet! Try scanning something first."

@app.route('/latest_processed')
def get_latest_processed():
    if processed_latest_image:
        return app.response_class(processed_latest_image, mimetype='image/jpeg')
    return "No cropped image yet!"


@app.route('/upload', methods=['POST'])
def upload():
    global latest_image, processed_latest_image
    try:
        image = request.get_data()
        latest_image = image # Save what the ESP32 sent us exactly

        if not image:
            return jsonify({"status": "ERROR", "msg": "No image data sent"})

        # --- STEP 1: Process and flatten the image first! ---
        has_shape, processed_image = crop_invoice(image)
        processed_latest_image = processed_image # Save the OpenCV result

        if has_shape == "BLUR":
            print("❌ Image was too blurry. Aborting Vision API!")
            return jsonify({"status": "BLUR"})

        # --- STEP 2: Feed the perfectly flat, cropped image to OCR ---
        text = extract_text(processed_image)
        
        # 🟢 DEBUGGING: Print exactly what OCR saw!
        print("====================================")
        print("🔍 RAW OCR TEXT EXTRACTED:")
        print(text if len(text) > 0 else "[OCR API RETURNED BLANK OR CRASHED]")
        print("====================================")

        # --- STEP 3: Validate the text ---
        if not is_invoice(text):
            safe_text = (text[:150] + '...') if len(text) > 150 else text
            # Sanitize for simpler JSON parsing
            safe_text = safe_text.replace("\n", " ").replace("\r", "").replace("\"", "'")
            return jsonify({"status": "NOT_INVOICE", "text": safe_text})

        gst = find_gst(text)

        if not gst:
            return jsonify({"status": "GST_MISSING"})

        try:
            # --- STEP 4: Save to Firebase ---
            ref = db.reference("GST_HISTORY")
            data = ref.get() or {}

            if gst in data:
                return jsonify({"status": "DUPLICATE_GST"})

            ref.child(gst).set({"ok": True})
            
        except Exception as fb_error:
            # If Google Vision worked, but Firebase failed, catch it here!
            print("FIREBASE CRASH LOG:", str(fb_error))
            return jsonify({"status": "FIREBASE_CRASH", "gst": gst, "error": str(fb_error)})

        return jsonify({"status": "VALID_INVOICE", "gst": gst})
        
    except Exception as e:
        print("VISION CRASH LOG:", traceback.format_exc())
        return jsonify({"status": "PYTHON_CRASH", "error": str(e)})


if __name__ == "__main__":
    app.run()
